baseURL = "https://lec-itatiba.pages.dev/"
languageCode = "pt-br"
title = "Lar Espírita Cristão"
theme = "mainroad"

[pagination]
  pagerSize = 5

[params]
  description = "Evangelho, acolhimento e consolação em Itatiba"
  subtitle = "Fora da Caridade não há Salvação"
  # O Mainroad usa essa cor vermelha padrão, combina com 'Cristão'
  highlightColor = "#e22d30" 

  [params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    # Adicionamos 'agenda_custom' que criaremos abaixo
    widgets = ["search", "recent", "agenda_custom", "categories"]

  [params.footer]
    copyrightText = "Lar Espírita Cristão"

[[menu.main]]
  name = "Início"
  url = "/"
  weight = 1

[[menu.main]]
  name = "História"
  url = "/historia/"
  weight = 2

# removi o agenda

[[menu.main]]
  name = "Pinga Fogo"
  url = "/pinga-fogo/"
  weight = 4
