baseURL = 'https://lec-itatiba.pages.dev/'
languageCode = 'pt-br'
title = 'Lar EspÃ­rita CristÃ£o'
theme = 'hugo-theme-cleanwhite'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  header_image = "images/foto-fachada.jpg"
  title = "Lar EspÃ­rita CristÃ£o"
  slogan = "Fora da Caridade nÃ£o hÃ¡ SalvaÃ§Ã£o"
  description = "Evangelho, acolhimento e consolaÃ§Ã£o Ã  luz da Doutrina EspÃ­rita."
  mainSections = ["post", "agenda", "eventos"]
  sidebar = true
  sidebar_about_description = "InstituiÃ§Ã£o dedicada ao estudo e Ã  prÃ¡tica da caridade cristÃ£. ğŸ™"

[[menu.main]]
  name = "InÃ­cio ğŸ "
  url = "/"
  weight = 1

[[menu.main]]
  name = "Atividades ğŸ—“ï¸"
  url = "/atividades/"
  weight = 2