baseURL = 'https://lec.pages.dev/'
languageCode = 'pt-br'
title = 'Lar EspÃ­rita CristÃ£o'
theme = 'hugo-theme-cleanwhite'
hasCoreEdge = true
enableEmoji = true # Habilita emojis nativos do Hugo como :peace_symbol:

# Permite que se use HTML dentro dos arquivos Markdown (essencial para mapas/botÃµes)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true 

[params]
  header_image = "img/home-bg.jpg"
  title = "Lar EspÃ­rita CristÃ£o"
  slogan = "Fora da Caridade nÃ£o hÃ¡ SalvaÃ§Ã£o"
  description = "Evangelho, acolhimento e consolaÃ§Ã£o Ã  luz da Doutrina EspÃ­rita."
  
  # AparÃªncia e Sidebar
  sidebar = true
  sidebar_about_description = "InstituiÃ§Ã£o dedicada ao estudo e Ã  prÃ¡tica da caridade cristÃ£. ğŸ™"
  featured_tags = true
  featured_condition_size = 1

  # --- ESPAÃ‡O PARA IMPLEMENTOS (Contador, Analytics, etc.) ---
 [params.csp]
  enable = true
  # 'self' significa imagens do prÃ³prio site
  img-src = " 'self' https://hits.seeyoufarm.com https://img.shields.io https://visitor-badge.laobi.icu " 

  # Redes Sociais e Contato
  # whatsapp = "5511999999999"
  # facebook = "perfil"

[[menu.main]]
  name = "InÃ­cio ğŸ "
  url = "/"
  weight = 1

[[menu.main]]
  name = "Atividades ğŸ—“ï¸"
  url = "/atividades/"
  weight = 2

[[menu.main]]
  name = "Estudos ğŸ“–"
  url = "/post/"
  weight = 3

[[menu.main]]
  name = "Como Ajudar â¤ï¸"
  url = "/ajuda/"
  weight = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]
