baseURL = "https://lecitatiba.com.br/"
languageCode = "pt-br"
title = "Lar Espírita Cristão"
theme = "mainroad"
publishDir = "docs"

[pagination]
  pagerSize = 5

[params]
  mainSections = ["post"]  # Isso força a listar o conteúdo da pasta 'post' na home
  description = "Evangelho, acolhimento e consolação em Itatiba"
  subtitle = "Fora da Caridade não há Salvação"
  # O Mainroad usa essa cor vermelha padrão
  highlightColor = "#e22d30"
  customCSS = ["css/custom.css"]
  favicon = "favicon.ico" 

  [params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    # Adicionei 'agenda_custom' que criei abaixo
    widgets = ["search", "recent", "agenda_custom", "mapa_custom", "categories"]

  [params.footer]
    copyrightText = "Lar Espírita Cristão"

[[menu.main]]
  name = "Início"
  url = "/"
  weight = 1

# [[menu.main]]
# name = "História"
# url = "/historia/"
# weight = 2

# removi o agenda

[[menu.main]]
  name = "Pinga-Fogo"
  url = "/pinga-fogo/"
  weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
